#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

host = data.get("host")
# agent.dump_env()
CREATE_SUPERUSER = data.get("CREATE_SUPERUSER", "admin:admin")
PORT = data.get("PORT", "8000")
BEHIND_HTTPS_PROXY = data.get("BEHIND_HTTPS_PROXY", "true")
BASE_URL = f"https://{host}"

web = {
    "CREATE_SUPERUSER": CREATE_SUPERUSER,
    "PORT": PORT,
    "BEHIND_HTTPS_PROXY": BEHIND_HTTPS_PROXY,
    "BASE_URL": BASE_URL,
}
agent.write_envfile("web.env", web)
