#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)
rdb = agent.redis_connect(use_replica=True)
smtp_settings = agent.get_smarthost_settings(rdb)

host = data.get("host")
# agent.dump_env()
CREATE_SUPERUSER = data.get("CREATE_SUPERUSER", "admin:admin")
PORT = data.get("PORT", "8000")
BEHIND_HTTPS_PROXY = data.get("BEHIND_HTTPS_PROXY", "true")
BASE_URL = f"https://{host}"

web = {
    "CREATE_SUPERUSER": CREATE_SUPERUSER,
    "PORT": PORT,
    "BEHIND_HTTPS_PROXY": BEHIND_HTTPS_PROXY,
    "BASE_URL": BASE_URL,
    "EMAIL_HOST": smtp_settings["host"],
    "EMAIL_HOST_USER": smtp_settings["username"],
    "EMAIL_HOST_PASSWORD": smtp_settings["password"],
    "EMAIL_PORT": smtp_settings["port"],
    "EMAIL_USE_TLS": "True" if smtp_settings["tls_verify"] else "False",
}
agent.write_envfile("web.env", web)
