#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
from warnings import filters
import agent
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# This is specific to you module, so you need to change it accordingly.


def generate_random_password(length):
    # Generate random bytes and convert them to a hexadecimal string
    random_bytes = os.urandom(length)
    password = random_bytes.hex()
    return password[:length]


# just before starting systemd unit
# agent.dump_env()
MYSQL_ROOT_PASSWORD = generate_random_password(16)
MYSQL_DATABASE = data.get("MYSQL_DATABASE", "bugsink")

mysql = {
    "MYSQL_ROOT_PASSWORD": MYSQL_ROOT_PASSWORD,
    "MYSQL_DATABASE": MYSQL_DATABASE,
}
agent.write_envfile("mysql.env", mysql)

SECRET_KEY = generate_random_password(64)
DATABASE_URL = f"mysql://root:{MYSQL_ROOT_PASSWORD}@mysql-app:3306/bugsink"

bugsink = {
    "DATABASE_URL": DATABASE_URL,
    "SECRET_KEY": SECRET_KEY,
}
agent.write_envfile("bugsink_db.env", bugsink)
